---
title: "Project 1"
output: html_document
---

library(plyr)
library(dplyr)
library(psych)
library(tidyverse) 
library(e1071)
library(scales)
library(reshape2)
library(usmap)
library(ggmap)
library(lubridate)
library(devtools)
library(viridis)
library(patchwork)
library(hrbrthemes)
library(kableExtra)
library(radarchart)
library(treemap)
library(fmsb)
library(maps)


```{r #Dataset import}
farmer_data <- read.csv('fmarket.csv', header = TRUE, sep = ',')
region_data <- read.csv('region.csv', header = TRUE, sep = ',')
colnames(region_data) <- c("State", "State_Code", "Region")
farmer_data <- merge(x = farmer_data, y = region_data, by = "State", all = TRUE)    
farmer_data[ , 24:58] <- ifelse(farmer_data[ , 24:58] == "Y", 1, 0)
rm(region_data)
```


```{r #Location of farmer market, echo=FALSE, message=FALSE, warning=FALSE}
#Location of farmer market

farmer_premises <- farmer_data%>% dplyr::select(Region, Location) %>% drop_na() 
farmer_premises$Government <- str_count(farmer_premises$Location, "government")
farmer_premises$Private <- str_count(farmer_premises$Location, "Private")
farmer_premises$Faith <- str_count(farmer_premises$Location, "Faith")
farmer_premises$Others <- str_count(farmer_premises$Location, "Other")

farmer_premises <- na.omit(farmer_premises)

farmer_premises <- farmer_premises %>%
  dplyr::group_by(Region) %>%
  dplyr::summarise_each(funs(sum), -Location)

farmer_premises <- farmer_premises[ , 2:5]
rownames(farmer_premises) <- c("Midwest", "Northeast", "South", "West")

set.seed(99)
farmer_premises <- rbind(rep(300,5) , rep(8,5) , farmer_premises)

# Color vector
colors_border <- c(rgb(0.2,0.5,0.5,0.9), rgb(0.8,0.2,0.5,0.9), rgb(0.7,0.5,0.1,0.9) )
colors_in <- c(rgb(0.2,0.5,0.5,0.4), rgb(0.8,0.2,0.5,0.4), rgb(0.7,0.5,0.1,0.4) )

#tiff("Premises count per Region.tiff", units="in", width=7, height=9, res=300)

#plot with default options:
radarchart(farmer_premises, axistype = 1,  pcol = colors_border, pfcol = colors_in, plwd = 4 , plty = 1,cglcol = "grey", cglty = 1, axislabcol = "grey", caxislabels = seq(0,300,75), cglwd = 0.8, vlcex = 0.8)

legend(x = 0.9, y = 1, legend = c("Midwest", "Northeast", "South", "West"), bty = "n", pch = 20 , col = colors_in, text.col = "black", cex = 1.2, pt.cex = 3)
rm(colors_border, colors_in, farmer_premises)
#dev.off()
```


```{r #Chloropeth map for Farmer markets across USA}
farmer_data_State <- farmer_data %>% dplyr::group_by(State) %>% dplyr::summarise(count=n())
farmer_data_State$State_abbr <- state.abb[match(farmer_data_State$State,state.name)]
farmer_data_State <- na.omit(farmer_data_State)

colnames(farmer_data_State) <- c("state", "count", "abbr")
#tiff("Statewise_Chloropleth.tiff", units="in", width=5, height=5, res=300)
plot_usmap(data = farmer_data_State, values = "count", color = "black") + 
  scale_fill_continuous(low = "lightyellow", high = "darkgreen", name = "State", label = scales::comma) +           theme(legend.position = "right") + labs(title = "\t \t \t \t \t \t \t \t \t \t \t \t \t \t Farmer Markets spread across USA")  
rm(farmer_data_State)
#dev.off()
```


```{r #Organic Farmer market locations}
farmer_data_org <- farmer_data %>% 
  dplyr::filter(Organic==1 & (farmer_data$State != "Alaska" & farmer_data$State != "Puerto Rico") & x > -150 & x < -50)       %>% drop_na()  %>% dplyr::select(x,y)

#tiff("Organic_plot.tiff", units="in", width=5, height=5, res=300)
usa <- map_data("usa") 
ggplot() + geom_polygon(data = usa, aes(x=long, y = lat, group = group)) + coord_fixed(1.3) + 
  geom_point(data = farmer_data_org, color="yellow", mapping = aes(x = x, y = y)) + 
  theme( panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
         panel.background = element_blank(), axis.line = element_line(colour = "grey")) + 
  labs(title = "\t \t \t Organic Farmer markets locations")
#dev.off()
rm(usa,farmer_data_org)

```


```{r #Social Media Analysis}
#Social media analysis
farmer_data_social <- farmer_data %>% dplyr::select(Website, Facebook, Twitter, Youtube, OtherMedia, Region)
farmer_data_social$Website <- ifelse(str_length(farmer_data_social$Website)>0,1,0) 
farmer_data_social$Facebook <- ifelse(str_length(farmer_data_social$Facebook)>0,1,0) 
farmer_data_social$Twitter <- ifelse(str_length(farmer_data_social$Twitter)>0,1,0) 
farmer_data_social$Youtube <- ifelse(str_length(farmer_data_social$Youtube)>0,1,0) 
farmer_data_social$OtherMedia <- ifelse(str_length(farmer_data_social$OtherMedia)>0,1,0) 
farmer_data_social <- na.omit(farmer_data_social)
farmer_data_social <- data.frame(farmer_data_social[!(is.na(farmer_data_social$Region) | 
                                              farmer_data_social$Region == ""), ])

farmer_data_social <- farmer_data_social %>% dplyr::group_by(Region) %>% 
                dplyr::summarise(Website = sum(Website), Facebook = sum(Facebook),
              Twitter = sum(Twitter), Youtube = sum(Youtube), Other_Media = sum(OtherMedia))
farmer_data_social <- farmer_data_social %>% 
  gather(c("Website" , "Facebook" , "Twitter" , "Youtube" , "Other_Media"), 
         key = "Social_Media" , value = "Value")  

#tiff("socialmedia.tiff", units="in", width=8, height=10, res=300)
ggplot(farmer_data_social, aes(fill=Social_Media, y=Value, x=Region, label = Value)) +
  geom_bar(position="dodge", stat="identity") + geom_text(position = position_dodge(width = 0.9),
vjust = -1, size = 3) + scale_fill_manual(values=c("#3b5998","#dcdd00","#00ACEE","#37ff32","#c4302b"))
rm(farmer_data_social)
#dev.off()
```


```{r #Date segmentation for seasonality, echo=FALSE, message=FALSE, warning=FALSE}
#First season
farmer_season <- farmer_data %>% dplyr::select(Season1Date, Season2Date, Season3Date, Region)
farmer_season <- data.frame(farmer_season[!(is.na(farmer_season$Region) | 
                                              farmer_season$Region == ""), ])
farmer_season <- data.frame(farmer_season[!(is.na(farmer_season$Season1Date) | 
                                                        farmer_season$Season1Date == ""), ])
  
farmer_season <- separate(data = farmer_season, col = Season1Date, 
                          into = c("Season1FromDate", "Season1ToDate"), sep = " to ")

farmer_season[ , 1] <- ifelse(!is.na(match(farmer_season[ , 1], month.name)) , 
                            match(farmer_season[ , 1], month.name), 
                            month(as.POSIXlt(farmer_season[ , 1], format="%m/%d/%Y")))

farmer_season <- data.frame(farmer_season[!(is.na(farmer_season$Season1FromDate) | 
                                              farmer_season$Season1FromDate == ""), ])

farmer_season[ , 2] <- ifelse(!is.na(match(farmer_season[ , 2], month.name)) , 
                            match(farmer_season[ , 2], month.name), 
                            month(as.POSIXlt(farmer_season[ , 2], format="%m/%d/%Y")))
 
farmer_season$Season1ToDate[which(is.na(farmer_season$Season1ToDate))] <- 12

#Second season

farmer_season <- separate(data = farmer_season, col = Season2Date, 
                          into = c("Season2FromDate", "Season2ToDate"), sep = " to ")

farmer_season[ , 3] <- ifelse(!is.na(match(farmer_season[,3], month.name)) , 
                            match(farmer_season[,3], month.name), 
                            month(as.POSIXlt(farmer_season[,3], format="%m/%d/%Y")))

farmer_season$Season2FromDate[which(is.na(farmer_season$Season2FromDate))] <- 0

farmer_season[ , 4] <- ifelse(!is.na(match(farmer_season[ , 4], month.name)) , 
                            match(farmer_season[ , 4], month.name), 
                            month(as.POSIXlt(farmer_season[ , 4], format="%m/%d/%Y")))

farmer_season[ , 4] <- ifelse(is.na(farmer_season[ , 4]) & farmer_season[ , 3] > 0, 12, NA)
 
#Third season

farmer_season <- separate(data = farmer_season, col = Season3Date, 
                          into = c("Season3FromDate", "Season3ToDate"), sep = " to ")
farmer_season[ , 5] <- ifelse(!is.na(match(farmer_season[ , 5], month.name)) , 
                            match(farmer_season[ , 5], month.name), 
                            month(as.POSIXlt(farmer_season[ , 5], format="%m/%d/%Y")))

farmer_season$Season3FromDate[which(is.na(farmer_season$Season3FromDate))] <- 0


farmer_season[ , 6] <- ifelse(!is.na(match(farmer_season[ , 6], month.name)) , 
                            match(farmer_season[ , 6], month.name), 
                            month(as.POSIXlt(farmer_season[ , 6], format="%m/%d/%Y")))

farmer_season[ , 6] <- ifelse(is.na(farmer_season[ , 4]) & farmer_season[ , 5] > 0, 12, NA)


#Creating the difference columns
farmer_season$Season1Diff = farmer_season$Season1ToDate - farmer_season$Season1FromDate
farmer_season$Season2Diff = farmer_season$Season2ToDate - farmer_season$Season2FromDate
farmer_season$Season3Diff = farmer_season$Season3ToDate - farmer_season$Season3FromDate

months <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec")
farmer_season[,months] <- 0


farmer_season[,3] <- ifelse(!is.na(farmer_season[ , 9]) & ( farmer_season[ , 8] == farmer_season[ , 9] |        farmer_season[,10] == farmer_season[ , 9] ) & farmer_season[ , 9] == 11 ,0,farmer_season[ , 3])
farmer_season[,5] <- ifelse(!is.na(farmer_season[ , 10]) & ( farmer_season[ , 9] == farmer_season[ , 10] |
                                                               farmer_season[ , 10] == farmer_season[, 8] ) & farmer_season[,10] == 11, 0, farmer_season[ , 5])


#Creating the months table for the seasonality
#Calculating for season1

current_month <- 0
end_month <- 0
for (i in 1:length(farmer_season$Season1Diff)) 
  {
  if(farmer_season$Season1Diff[i]>=0 & !is.na(farmer_season$Season1Diff[i]) & farmer_season$Season1FromDate[i]>0)
 {
    current_month <- farmer_season$Season1FromDate[i]
    end_month <- farmer_season$Season1ToDate[i]
    k <- 0
    for (j in current_month:end_month) 
      {
      farmer_season[i , current_month + k + 10] = farmer_season[i , current_month + k + 10] + 1 
      k=k+1
      }
  }
}

#Calculating for season2

current_month <- 0
end_month <- 0
for (i in 1:length(farmer_season$Season2Diff)) 
{
  if(farmer_season$Season2Diff[i]>=0 & !is.na(farmer_season$Season2Diff[i]) & farmer_season$Season2FromDate[i]>0 & !is.na(farmer_season$Season2FromDate[i]))
  {
    current_month <- farmer_season$Season2FromDate[i]
    end_month <- farmer_season$Season2ToDate[i]
    k <- 0
    for (j in current_month:end_month) 
    {
      farmer_season[i , current_month + k + 10] = farmer_season[i , current_month + k + 10] + 1 
      k=k+1
    }
  }
}

#Calculating for season3
current_month <- 0
end_month <- 0
for (i in 1:length(farmer_season$Season3Diff)) 
{
  if(farmer_season$Season3Diff[i]>=0 & !is.na(farmer_season$Season3Diff[i]) & farmer_season$Season3FromDate[i]>0 &  !is.na(farmer_season$Season3FromDate[i]))
  {
    current_month <- farmer_season$Season3FromDate[i]
    end_month <- farmer_season$Season3ToDate[i]
    k <- 0
    for (j in current_month:end_month) 
    {
      farmer_season[i , current_month + k + 10] = farmer_season[i , current_month + k + 10] + 1 
      k=k+1
    }
  }
}


#Farmer markets open all year
farmer_all_time <- farmer_season %>% filter(Season1Diff==11 | Season2Diff==11 | Season2Diff==11) %>% group_by(Region) %>% select(Region) %>% dplyr::summarise(count=n())

#tiff("All year opened markets.tiff", units="in", width=8, height=10, res=300)
ggplot(farmer_all_time, aes(x=Region, y=count)) +
  geom_segment( aes(x=Region, xend=Region, y=0, yend=count)) +
  geom_point( size=5, color="black", fill=alpha("darkgreen", 1), alpha=0.7, shape=21, stroke=2) + 
  theme( panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
         panel.background = element_blank(), axis.line = element_line(colour = "grey") , axis.text=element_text(size=14) ,  
         axis.title=element_text(size=14,face="bold")) + labs(title = "\t \t \t \t \t \t Number of Farmer Markets opened all year") + ylab("Number of farmer markets")
#dev.off()


farmer_season <- farmer_season %>% group_by(Region) %>% summarise_all(funs(sum))
farmer_season <- farmer_season %>% gather(c("Jan", "Feb", "Mar", "Apr","May","Jun","Jul","Aug","Sept","Oct","Nov","Dec"),
                                        key = Months, value=value)

#tiff("season.tiff", units="in", width=5, height=5, res=300)

ggplot(data=farmer_season, aes(x= Months , y = value , col = Region , group = Region)) + 
  geom_line() + geom_point() + labs(title = "", x = "", y = "") + scale_x_discrete(limits = month.abb) +
  theme( panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "grey")) + 
  labs(title = "\t \t \t \t \t \t Farmer markets availability month-wise")

#dev.off()
rm(farmer_season, farmer_all_time, months, i, j, k, end_month, current_month)
```

```{r #Products Circular bar plot }

farmer_products<- farmer_data[c(30:58,61)]
farmer_products <- data.frame(farmer_products[!(is.na(farmer_products$Region) | 
                                                  farmer_products$Region == ""), ])

farmer_products <- farmer_products %>% group_by(Region) %>% dplyr::summarise_all(funs(sum))
farmer_products <- farmer_products %>% gather(c(2:30), key = "products" , value = "value" )

empty_bar <- 4
to_add <- data.frame( matrix(NA, empty_bar*nlevels(farmer_products$Region), ncol(farmer_products)) )
colnames(to_add) <- colnames(farmer_products)
farmer_products <- farmer_products %>% arrange(Region, value)
farmer_products$id <- seq(1, nrow(farmer_products))

# Get the name and the y position of each label
label_data <- farmer_products
number_of_bar <- nrow(label_data)
angle <- 90 - 360 * (label_data$id-0.5) /number_of_bar     
label_data$hjust <- ifelse( angle < -90, 1, 0)
label_data$angle <- ifelse(angle < -90, angle+180, angle)


base_data <- farmer_products %>% 
  group_by(Region) %>% 
  summarize(start=min(id), end=max(id) - empty_bar) %>% 
  rowwise() %>% 
  mutate(title=mean(c(start, end)))


grid_data <- base_data
grid_data$end <- grid_data$end[ c( nrow(grid_data), 1:nrow(grid_data)-1)] + 1
grid_data$start <- grid_data$start - 1
grid_data <- grid_data[-1,]


#tiff("products.tiff", units="in", width=8, height=8, res=300)

ggplot(farmer_products, aes(x=as.factor(id), y=value, fill=Region)) +     
  geom_bar(stat="identity", alpha=0.5) + 
  ylim(-1700,1700) +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm") 
  ) +
  coord_polar() + geom_text(data=label_data, aes(x=id, y=value+10, label=products, hjust=hjust), color="black",
            fontface="bold",alpha=0.6, size=2.5, angle= label_data$angle, inherit.aes = FALSE ) +
  geom_segment(data=base_data, aes(x = start, y = -5, xend = end, yend = -5), colour = "black", alpha=0.8, size=0.6 , inherit.aes = FALSE )  +
  geom_text(data=base_data, aes(x = title, y = -18, label=Region), hjust=c(1,1,0,0), colour = "black", alpha=0.8, size=4, fontface="bold", inherit.aes = FALSE)
rm(farmer_products, base_data, grid_data, to_add, label_data, angle, number_of_bar, empty_bar)
#dev.off()

```

```{r #Products State wise Circular plot}

farmer_state_product <- farmer_data %>% select(c(29:58,60)) %>% drop_na() %>% group_by(State_Code) %>%
  dplyr::summarise_all(funs(sum))

farmer_state_product$Count <- rowSums( farmer_state_product[,2:31])
farmer_state_product <- farmer_state_product %>% arrange(desc(Count)) %>% mutate(State_Code=factor(State_Code, State_Code))


empty_bar=10

to_add = matrix(NA, empty_bar, ncol(farmer_state_product))
colnames(to_add) = colnames(farmer_state_product)
farmer_state_product=rbind(farmer_state_product, to_add)
farmer_state_product$id=seq(1, nrow(farmer_state_product))

# Get the name and the y position of each label
label_tmp=farmer_state_product
number_of_bar=nrow(label_tmp)
angle= 90 - 360 * (label_tmp$id-0.5) /number_of_bar     
label_tmp$hjust<-ifelse( angle < -90, 1, 0)
label_tmp$angle<-ifelse(angle < -90, angle+180, angle)
label_tmp$State_Code <- gsub("United States", "US", label_tmp$State_Code)
label_tmp$State_Code <- paste(label_tmp$State_Code, " (", label_tmp$Count,")", sep="")

# Make the plot

#tiff("productsState.tiff", units="in", width=8, height=10, res=300)
ggplot(farmer_state_product, aes(x=as.factor(id), y=Count)) + 
  geom_bar(stat="identity", fill=alpha("#69b3a2", 0.8)) + 
  ylim(-7000,8000) +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm")) +
  coord_polar(start = 0) + 
  geom_text(data=label_tmp, aes(x=id, y=Count+200, label=State_Code ), color="black", fontface="bold",alpha=0.6, size=2.5, angle= label_tmp$angle, hjust=label_tmp$hjust, inherit.aes = FALSE ) +
  geom_text( aes(x=24, y=8000, label="Which State sells more products?"), color="black", inherit.aes = FALSE)
rm(farmer_state_product, label_tmp, angle,empty_bar, to_add, number_of_bar)
#dev.off()

```

```{r #Payment program}

farmer_payment <- farmer_data %>%  dplyr::select(SFMNP, SNAP, WICcash, WIC) %>% dplyr::summarise_all(funs(sum))

farmer_payment <- data.frame(t(farmer_payment), stringsAsFactors ="F")
farmer_payment$Category <- rownames(farmer_payment)
colnames(farmer_payment) <- c("Count","Category")
farmer_payment$fraction <- 100*(farmer_payment$Count/sum(farmer_payment$Count))

# Compute the cumulative percentages (top of each rectangle)
farmer_payment$ymax <- cumsum(farmer_payment$fraction)

# Compute the bottom of each rectangle
farmer_payment$ymin <- c(0, head(farmer_payment$ymax, n=-1))

# Compute label position
farmer_payment$labelPosition <- (farmer_payment$ymax + farmer_payment$ymin) / 2

# Compute a good label
farmer_payment$label <- paste0(farmer_payment$Category, "\n", farmer_payment$Count)

# Make the plot
#tiff("sfmnp.tiff", units="in", width=8, height=8, res=300)
ggplot(farmer_payment, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=Category)) +
  geom_rect() +
  geom_text( x=1, aes(y=labelPosition, label=label, color=Category), size=6) + 
  scale_fill_brewer(palette=5) +
  scale_color_brewer(palette=5) +
  coord_polar(theta="y") +
  xlim(c(-1, 4)) +
  theme_void() +
  theme(legend.position = "none")
rm(farmer_payment)
#dev.off()
```

```{r #States with highest SFMNP farmer markets}

farmer_payment_states <- farmer_data %>%  dplyr::select(State, State_Code ,SFMNP, SNAP, WICcash, WIC) %>% na.omit() %>% dplyr::group_by(State, State_Code) %>% dplyr::summarize_at(vars(SFMNP, SNAP, WICcash, WIC), funs(sum))

farmer_payment_states$Count <- rowSums( farmer_payment_states[,3:6] )

farmer_payment_states <- farmer_payment_states %>% arrange(desc(Count)) %>% head(5)

#tiff("payment_states.tiff", units="in", width=8, height=8, res=300)
ggplot(data = farmer_payment_states, aes(x=reorder(State, Count) ,y=Count)) +
    geom_bar(stat="identity", fill="#105232", alpha=.6, width=.4) +
    coord_flip() + theme( panel.border = element_blank(), panel.grid.major = element_blank(), 
                          panel.grid.minor =element_blank(), panel.background = element_blank(), 
                          axis.line =element_line(colour = "grey")) +
    xlab("States") + ylab("Special Payment Programs accepted")
#dev.off()
rm(farmer_payment_states)

```

```{r #State with highest social media presence}

farmer_data_social_State <- farmer_data %>% dplyr::select(Website, Facebook, Twitter, Youtube, OtherMedia, State)
farmer_data_social_State$Website <- ifelse(str_length(farmer_data_social_State$Website)>0,1,0) 
farmer_data_social_State$Facebook <- ifelse(str_length(farmer_data_social_State$Facebook)>0,1,0) 
farmer_data_social_State$Twitter <- ifelse(str_length(farmer_data_social_State$Twitter)>0,1,0) 
farmer_data_social_State$Youtube <- ifelse(str_length(farmer_data_social_State$Youtube)>0,1,0) 
farmer_data_social_State$OtherMedia <- ifelse(str_length(farmer_data_social_State$OtherMedia)>0,1,0) 
farmer_data_social_State <- na.omit(farmer_data_social_State)
farmer_data_social_State <- data.frame(farmer_data_social_State[!(is.na(farmer_data_social_State$State) | 
                                              farmer_data_social_State$State == ""), ])

farmer_data_social_State <- farmer_data_social_State %>% dplyr::group_by(State) %>% dplyr::summarise_all(funs(sum))
farmer_data_social_State$Count <- rowSums( farmer_data_social_State[,2:6] )
farmer_data_social_State <- farmer_data_social_State %>% arrange(desc(Count)) %>% head(5)

#tiff("social_media_states.tiff", units="in", width=8, height=8, res=300)
ggplot(data = farmer_data_social_State, aes(x=reorder(State, Count) ,y=Count)) +
    geom_bar(stat="identity", fill="#2D4694", alpha=.6, width=.4) +
    coord_flip() + theme( panel.border = element_blank(), panel.grid.major = element_blank(), 
                          panel.grid.minor =element_blank(), panel.background = element_blank(), 
                          axis.line =element_line(colour = "grey")) +
    xlab("States") + ylab("Social media Presence available")
#dev.off()

rm(farmer_data_social_State)

```


```{r #State and premises}

farmer_premises_State <- farmer_data%>% dplyr::select(State, Location) %>% drop_na() 
farmer_premises_State$Government <- str_count(farmer_premises_State$Location, "government")
farmer_premises_State$Private <- str_count(farmer_premises_State$Location, "Private")
farmer_premises_State$Faith <- str_count(farmer_premises_State$Location, "Faith")
farmer_premises_State$Others <- str_count(farmer_premises_State$Location, "Other")

farmer_premises_State <- na.omit(farmer_premises_State)

farmer_premises_State <- farmer_premises_State %>%
  dplyr::group_by(State) %>%
    dplyr::summarise_each(funs(sum), -Location)
farmer_premises_State$Count <- rowSums( farmer_premises_State[,2:5] )
farmer_premises_State <- farmer_premises_State %>% arrange(desc(Count)) %>% head(5)

tiff("premises_states.tiff", units="in", width=8, height=8, res=300)
ggplot(data = farmer_premises_State, aes(x=reorder(State, Count) ,y=Count)) +
    geom_bar(stat="identity", fill="#84BD85", alpha=.6, width=.4) +
    coord_flip() + theme( panel.border = element_blank(), panel.grid.major = element_blank(), 
                          panel.grid.minor =element_blank(), panel.background = element_blank(), 
                          axis.line =element_line(colour = "grey")) +
    xlab("States") + ylab("Premises available")
dev.off()

rm(farmer_premises_State)

```

